language: ruby
rvm:
- 2.2.0
before_script:
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bundle exec rake db:migrate
cache: bundler
bundler_args: "--without production development"
